import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { motion, AnimatePresence } from 'framer-motion';
import {
  HiOutlineSparkles,
  HiOutlineShieldCheck,
  HiOutlineExclamation,
  HiOutlineCheck,
  HiOutlineArrowRight,
  HiOutlineMusicNote,
  HiOutlineRefresh,
  HiOutlineLightningBolt,
} from 'react-icons/hi';
import { cn } from '../../utils/helpers';

const DEFAULT_DAILY_INSIGHTS = [
  {
    id: 'insight-1',
    category: 'Warning',
    badgeType: 'warning',
    badgeText: 'Duplicate Subscriptions',
    title: 'You are paying for three music subscriptions simultaneously',
    description: 'SubSense AI identified active billings for Spotify Premium ($11.99), Apple Music ($10.99), and YouTube Music ($13.99) across connected accounts.',
    savingsText: 'Save $22.98/mo',
    confidenceScore: 99.4,
    icon: HiOutlineMusicNote,
    actionLabel: 'Consolidate Music Plans',
  },
  {
    id: 'insight-2',
    category: 'Savings',
    badgeType: 'savings',
    badgeText: 'Unused SaaS Seat',
    title: 'Canceling Canva Pro saves $79.99/mo ($960/yr)',
    description: 'Zero logins or design exports detected in the last 45 days. One-click cancellation will prevent upcoming auto-debit.',
    savingsText: 'Save $960/yr',
    confidenceScore: 98.7,
    icon: HiOutlineSparkles,
    actionLabel: '1-Click Cancel Canva',
  },
  {
    id: 'insight-3',
    category: 'Warning',
    badgeType: 'warning',
    badgeText: 'Budget Overrun Alert',
    title: 'You will exceed your monthly entertainment budget next week',
    description: 'Projected spend is trending 24% above your target threshold due to unannounced streaming price hikes.',
    savingsText: 'Budget Guard',
    confidenceScore: 94.2,
    icon: HiOutlineExclamation,
    actionLabel: 'Adjust Budget Limit',
  },
  {
    id: 'insight-4',
    category: 'Recommendation',
    badgeType: 'recommendation',
    badgeText: 'Upcoming Due Date',
    title: 'Electricity & Utility bill ($145.00) is due tomorrow',
    description: 'Autopay is not enabled for this biller. Pay now with 1-tap or set automated liquidity reminder.',
    savingsText: 'Due Tomorrow',
    confidenceScore: 99.9,
    icon: HiOutlineLightningBolt,
    actionLabel: 'Pay Bill Now',
  },
];

const AIInsightsPanel = ({
  insights = DEFAULT_DAILY_INSIGHTS,
  className = '',
  onActionClick,
}) => {
  const [items, setItems] = useState(insights);
  const [executingId, setExecutingId] = useState(null);
  const [executedIds, setExecutedIds] = useState([]);

  const handleAction = (item) => {
    setExecutingId(item.id);
    setTimeout(() => {
      setExecutingId(null);
      setExecutedIds((prev) => [...prev, item.id]);
      if (onActionClick) onActionClick(item);
    }, 900);
  };

  const getBadgeStyle = (badgeType) => {
    switch (badgeType) {
      case 'savings':
        return 'bg-[#3FA972]/15 text-[#3FA972] border-[#3FA972]/30';
      case 'warning':
        return 'bg-[#D65C4F]/15 text-[#D65C4F] border-[#D65C4F]/30';
      case 'recommendation':
      default:
        return 'bg-[#C2A155]/15 text-[#C2A155] border-[#C2A155]/30';
    }
  };

  return (
    <div className={cn('relative rounded-xl border border-[#F3F1EA]/10 bg-[#171A18] p-6 shadow-2xl', className)}>
      {/* Header Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#F3F1EA]/10 pb-5">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#C2A155] text-[#0D0F0E] font-bold">
            <HiOutlineSparkles className="h-5 w-5" />
          </div>

          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-xl font-display font-bold text-[#F3F1EA] tracking-tight">
                Autonomous AI Insights
              </h2>
              <span className="rounded bg-[#C2A155]/20 px-2 py-0.5 text-[10px] font-mono font-bold text-[#C2A155] border border-[#C2A155]/30 uppercase">
                LIVE AUDIT
              </span>
            </div>
            <p className="text-xs text-[#96988F] font-sans">
              Generated by fine-tuned SubSense Copilot • Updated 2 mins ago
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 rounded-lg border border-[#F3F1EA]/10 bg-[#0D0F0E] px-3 py-1.5 font-mono text-xs text-[#F3F1EA]">
          <HiOutlineShieldCheck className="h-4 w-4 text-[#3FA972]" />
          <span>98.5% AI Confidence</span>
        </div>
      </div>

      {/* Insights List */}
      <div className="mt-6 space-y-4">
        <AnimatePresence mode="popLayout">
          {items.map((item) => {
            const Icon = item.icon || HiOutlineSparkles;
            const isExecuted = executedIds.includes(item.id);
            const isExecuting = executingId === item.id;

            return (
              <motion.div
                key={item.id}
                layout
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.98 }}
                className={cn(
                  'flex flex-col justify-between rounded-lg border p-4 transition-all duration-200 sm:flex-row sm:items-center',
                  isExecuted
                    ? 'border-[#3FA972]/40 bg-[#3FA972]/5'
                    : 'border-[#F3F1EA]/10 bg-[#0D0F0E] hover:border-[#C2A155]/40'
                )}
              >
                <div className="flex items-start gap-3.5 min-w-0 flex-1 pr-2">
                  <div className={cn('flex h-9 w-9 shrink-0 items-center justify-center rounded border', getBadgeStyle(item.badgeType))}>
                    {isExecuted ? <HiOutlineCheck className="h-5 w-5 text-[#3FA972]" /> : <Icon className="h-4 w-4" />}
                  </div>

                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2 mb-1">
                      <span className={cn('rounded px-2 py-0.5 text-[10px] font-mono font-bold uppercase', getBadgeStyle(item.badgeType))}>
                        {item.badgeText}
                      </span>
                      <span className="text-[10px] font-mono font-bold text-[#3FA972]">{item.savingsText}</span>
                      <span className="text-[10px] font-mono text-[#96988F]">• {item.confidenceScore}% match</span>
                    </div>

                    <h3 className="text-sm font-display font-bold text-[#F3F1EA] leading-snug">
                      {item.title}
                    </h3>

                    <p className="mt-1 text-xs text-[#96988F] leading-relaxed font-sans">
                      {item.description}
                    </p>
                  </div>
                </div>

                <div className="mt-3 flex shrink-0 items-center justify-end sm:mt-0 sm:pl-4">
                  <button
                    type="button"
                    onClick={() => handleAction(item)}
                    disabled={isExecuting || isExecuted}
                    className={cn(
                      'inline-flex items-center gap-1.5 rounded px-3.5 py-1.5 text-xs font-bold transition-all cursor-pointer shadow-sm',
                      isExecuted
                        ? 'bg-[#3FA972]/20 text-[#3FA972] border border-[#3FA972]/40 cursor-default font-mono'
                        : isExecuting
                        ? 'bg-[#C2A155]/30 text-[#C2A155] border border-[#C2A155]/40 font-mono'
                        : 'bg-[#C2A155] text-[#0D0F0E] hover:bg-[#D4B468]'
                    )}
                  >
                    {isExecuting ? (
                      <>
                        <HiOutlineRefresh className="h-3.5 w-3.5 animate-spin" />
                        <span className="font-mono">Applying...</span>
                      </>
                    ) : isExecuted ? (
                      <>
                        <HiOutlineCheck className="h-3.5 w-3.5" />
                        <span className="font-mono">Executed</span>
                      </>
                    ) : (
                      <>
                        <span>{item.actionLabel}</span>
                        <HiOutlineArrowRight className="h-3.5 w-3.5" />
                      </>
                    )}
                  </button>
                </div>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>
    </div>
  );
};

AIInsightsPanel.propTypes = {
  insights: PropTypes.array,
  className: PropTypes.string,
  onActionClick: PropTypes.func,
};

export default AIInsightsPanel;
